Repository planetarium/NineChronicles.SeasonPass, pull requests merged in 2023-11, with the labels that each got.

#17 Block tracker & Brave exp handler
  common/alembic/versions/9a4dafd6163e_add_exp_model.py
  common/alembic/versions/f1944309b46c_add_action_handle_history_tables.py
  common/enums.py
  common/models/__init__.py
  common/models/action.py
  common/models/season_pass.py
  common/utils/season_pass.py
  poetry.lock
  pyproject.toml
  season_pass/api/season_pass.py
  season_pass/schemas/season_pass.py
  worker/__init__.py
  worker/block_tracker.py
  worker/brave_handler.py
  worker/schemas/__init__.py
  worker/schemas/action.py
  worker/schemas/sqs.py
  worker/unloader.py
  worker/worker_cdk_stack.py
Labels: enhancement, Extra Large

#18 Add unload type field to tx memo
  worker/unloader.py
Labels: enhancement, Extra Small

#20 Add missing file
  worker/block_tracker.py
  worker/utils/stake.py
Labels: bug, Extra Small

#21 Update JWT verification logic with docs
  season_pass/api/user.py
  season_pass/utils.py
Labels: enhancement, Small

#19 Handle max level claim reward
  common/models/user.py
  common/utils/season_pass.py
  season_pass/api/user.py
Labels: enhancement, Small

#22 Add season pass reward list script
  .github/scripts/upload_host.py
  .github/workflows/deploy.yml
  .gitignore
  poetry.lock
  pyproject.toml
  scripts/fetch_reward.py
  scripts/google.py
Labels: enhancement, Large

#23 Pass slack message condition in manual
  .github/workflows/deploy.yml
  .github/workflows/slack_message.yml
  .github/workflows/synth.yml
  .github/workflows/test.yml
Labels: bug, Extra Small

#24 Fix available rewards and exp calculate logic
  common/models/user.py
  season_pass/api/user.py
  season_pass/settings/__init__.py
Labels: bug, Extra Small

#25 Do not send SQS message when no available rewards
  season_pass/api/user.py
Labels: bug, Extra Small

#26 Add missing item ID 800201
  worker/consts.py
Labels: bug, Extra Small

#27 Split queue by purpose
  common/shared_cdk_stack.py
  season_pass/api_cdk_stack.py
  worker/worker_cdk_stack.py
Labels: bug, Extra Small

#28 Keep deprecated resource for depencdency
  common/shared_cdk_stack.py
Labels: bug, Extra Small

#29 Check changeset before merge
  .github/workflows/synth.yml
  season_pass/api_cdk_stack.py
  worker/worker_cdk_stack.py
Labels: bug, Extra Small

#30 Reference splitted new queues
  season_pass/api_cdk_stack.py
  worker/worker_cdk_stack.py
Labels: bug, Extra Small

#31 Remove deprecated queue
  common/shared_cdk_stack.py
Labels: bug, Extra Small

#32 Update github actions with Docker
  .github/workflows/build_docker.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/slack_message.yml
  .github/workflows/synth.yml
  .github/workflows/test.yml
  Dockerfile
Labels: enhancement, Medium

#33 Approval_notice needs test and synth
  .github/workflows/main.yml
Labels: enhancement, Extra Small

#34 Add service and change target directory
  Dockerfile
  block_tracker.service
Labels: enhancement, Extra Small

#35 Add EC2 role for block tracker
  .github/workflows/slack_message.yml
  worker/worker_cdk_stack.py
Labels: enhancement, Extra Small

#36 Bugfix/authorization
  season_pass/settings/__init__.py
  season_pass/utils.py
Labels: bug, Extra Small

#37 Lambda block tracker
  worker/block_tracker.py
  worker/worker_cdk_stack.py
Labels: enhancement, Medium

#38 Update brave handler
  common/alembic/versions/e1d1d1c1f914_chane_action_type_column_type.py
  common/models/action.py
  worker/block_tracker.py
  worker/brave_handler.py
Labels: bug, enhancement, Small

#39 Manual Tx. signer function for ad-hoc tx signing request
  worker/manual_signer.py
  worker/worker_cdk_stack.py
Labels: enhancement

#40 Fix wrong data
  worker/brave_handler.py
Labels: bug

#42 Multiplanetary
  common/alembic/versions/b0b9cb232f67_add_planet_id_columns.py
  common/enums.py
  common/models/user.py
  season_pass/api/tmp.py
  season_pass/api/user.py
  season_pass/schemas/tmp.py
  season_pass/schemas/user.py
  worker/brave_handler.py
Labels: enhancement

#43 Treat all addresses as lower case
  season_pass/api/user.py
  season_pass/schemas/tmp.py
  season_pass/schemas/user.py
  worker/brave_handler.py
Labels: bug, Extra Small

#41 Docker image is no longer required
  .github/workflows/main.yml
Labels: Extra Small

#44 Bugfix/brave handler
  common/alembic/versions/00a050a705c2_add_details_to_action_history.py
  common/models/action.py
  worker/brave_handler.py
Labels: bug, Small

#45 Multiplanetary
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  common/alembic/versions/1eeafab14cd5_.py
  common/alembic/versions/f0229efb5723_add_planet_id_to_block_and_action_.py
  common/models/action.py
  common/models/user.py
  season_pass/api/user.py
  season_pass/schemas/user.py
  worker/block_tracker.py
  worker/brave_handler.py
  worker/worker_cdk_stack.py
Labels: enhancement, Medium

#47 Feature/multiplanetary
  worker/block_tracker.py
  worker/brave_handler.py
  worker/utils/stake.py
  worker/worker_cdk_stack.py
Labels: bug, enhancement, Small

#48 Bugfix/multiplanetary
  common/alembic/versions/8f846cbfffec_block_identifies_by_both_planet_id_and_.py
  common/models/action.py
  season_pass/schemas/tmp.py
  season_pass/schemas/user.py
  worker/brave_handler.py
Labels: bug, Extra Small

#49 Use planet_id in GQL module
  worker/unloader.py
  worker/utils/_graphql.py
Labels: enhancement, Small

#50 Fix using multiplanetary
  common/__init__.py
  worker/utils/_graphql.py
  worker/worker_cdk_stack.py
Labels: bug, Extra Small

#51 Update DB related things
  common/alembic/versions/92c0120a4566_update_unique_constraint_of_claim_table.py
  common/models/user.py
  worker/unloader.py
  worker/utils/_graphql.py
Labels: bug, Extra Small

#53 Multiplanetary
  worker/brave_handler.py
Labels: bug, Extra Small

#54 Use passed planet_id
  worker/brave_handler.py
Labels: bug

#55 Update integrity error message
  worker/brave_handler.py
Labels: bug

#52 Bugfix/authorization
  season_pass/api/user.py
Labels: enhancement, Extra Small

#56 Improve logging
  common/__init__.py
  season_pass/main.py
  worker/block_tracker.py
  worker/brave_handler.py
  worker/unloader.py
Labels: enhancement

#57 Handle integrity error with duplicated block
  worker/brave_handler.py
Labels: enhancement

#58 Send premium reward
  season_pass/api/user.py
  season_pass/schemas/user.py
  worker/utils/_graphql.py
Labels: enhancement, Medium

#59 Refactor common modules
  common/utils/_crypto.py
  common/utils/_graphql.py
  season_pass/api/user.py
  worker/manual_signer.py
  worker/unloader.py
Labels: enhancement, Extra Small

#60 Update required packages
  poetry.lock
  pyproject.toml
Labels: enhancement, Extra Small

#61 Send instance reward through unloader
  season_pass/api/user.py
  worker/unloader.py
Labels: enhancement

#62 Remove problematic import
  common/utils/_graphql.py
  season_pass/api/user.py
  season_pass/schemas/user.py
  worker/unloader.py
Labels: bug, Extra Small

#63 Reformat claim data
  season_pass/api/user.py
  worker/unloader.py
Labels: bug, Extra Small

#64 Make claims JSON serializable
  season_pass/api/user.py
Labels: bug, Extra Small

#65 Apply change Claim reward schema
  common/utils/_graphql.py
  worker/unloader.py
Labels: bug

#66 Sanitize address to starts with 0x
  season_pass/schemas/user.py
Labels: bug, Extra Small

#67 Get rid of repeating level from level dict
  worker/brave_handler.py
Labels: bug, Extra Small

#68 Fix wrong GQL params
  common/utils/_graphql.py
Labels: bug, Extra Small

#69 Bugfix/missing brave
  season_pass/api/user.py
  worker/block_tracker.py
  worker/worker_cdk_stack.py
Labels: bug, enhancement, Small

#70 Fix send message to dedicated SQS
  worker/worker_cdk_stack.py
Labels: bug

#71 Revive old queue_url for compatibility
  worker/worker_cdk_stack.py
Labels: bug

#73 Bugfix/max level
  common/models/user.py
  common/utils/season_pass.py
  season_pass/api/user.py
  worker/brave_handler.py
Labels: bug

#72 Feature/instant brave exp
  common/alembic/versions/993ab160a6fc_add_instant_reward_column_to_season.py
  common/models/season_pass.py
  season_pass/api/user.py
Labels: enhancement, Extra Small, alembic

#74 Add SQS permission to each tracker
  worker/worker_cdk_stack.py
Labels: bug, Medium

#75 Add policy for compatibility
  worker/worker_cdk_stack.py
Labels: bug, Extra Small

#79 Revive old schema data for backward compatibility
  season_pass/api/season_pass.py
  season_pass/schemas/season_pass.py
Labels: bug, Small

#80 Fix wrong memo position
  common/utils/_graphql.py
Labels: bug, Extra Small

#78 Check online planet
  common/utils/_graphql.py
  worker/worker_cdk_stack.py
Labels: bug, Extra Small

#81 Feature/test ec2 stack
  .github/scripts/init_block_tracker.sh
  .github/workflows/main.yml
  common/shared_cdk_stack.py
  worker/worker_cdk_stack.py
Labels: enhancement

#84 Claim Tx Tracker
  worker/tx_tracker.py
  worker/worker_cdk_stack.py
Labels: enhancement, Medium

#85 Fix wrong qurey statement and change variable names
  worker/tx_tracker.py
  worker/worker_cdk_stack.py
Labels: bug, Extra Small

#87 Fix wrong return type
  worker/tx_tracker.py
Labels: bug, Extra Small

#88 Update CDK stack
  common/shared_cdk_stack.py
  worker/worker_cdk_stack.py
Labels: enhancement, Extra Small

#89 claim does not have msg column
  worker/tx_tracker.py
Labels: bug, Extra Small

#90 Update right claim status
  worker/tx_tracker.py
Labels: bug

#91 0.2.0
  common/shared_cdk_stack.py
  worker/tx_tracker.py
  worker/worker_cdk_stack.py
Labels: Large

#92 Commit claim data before enqueue to SQS
  season_pass/api/user.py
Labels: Extra Small

#86 Add unique constraint to user_season_pass
  common/alembic/versions/77e337ab3c79_add_unique_constraint_to_user_season_.py
  common/models/user.py
  season_pass/api/user.py
Labels: enhancement, Extra Small

#93 Create block tracking status API
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  season_pass/main.py
Labels: Extra Small

#94 0.2.0
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/alembic/versions/77e337ab3c79_add_unique_constraint_to_user_season_.py
  common/models/user.py
  season_pass/api/user.py
  season_pass/api_cdk_stack.py
  season_pass/main.py
Labels: Small

#95 Backmerge 0.2.0 to development
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/alembic/versions/77e337ab3c79_add_unique_constraint_to_user_season_.py
  common/models/user.py
  common/shared_cdk_stack.py
  season_pass/api/user.py
  season_pass/api_cdk_stack.py
  season_pass/main.py
  worker/tx_tracker.py
  worker/worker_cdk_stack.py
Labels: Large

#98 Get and send tx_id to handler
  worker/block_tracker.py
Labels: enhancement

#102 Block scraper to service
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  common/__init__.py
  poetry.lock
  pyproject.toml
  worker/block_scraper.py
  worker/worker_cdk_stack.py
Labels: enhancement, Large

#96 Fix GQL host to full-state to avoid rate limit
  common/utils/_graphql.py
  worker/brave_handler.py
  worker/worker_cdk_stack.py
Labels: bug, Extra Small

#104 Make scraper service to run
  worker/block_scraper.py
  worker/worker_cdk_stack.py
Labels: enhancement, Extra Small

#105 Update manual signer to do freqently asked requests
  worker/manual_signer.py
  worker/worker_cdk_stack.py
Labels: enhancement

#106 Setup but disable block scraper
  worker/block_scraper.py
  worker/worker_cdk_stack.py
Labels: enhancement, wontfix

#107 Return INVALID status when error occurs
  worker/tx_tracker.py
  worker/worker_cdk_stack.py
Labels: bug

#108 Release/0.2.1
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/utils/_graphql.py
  poetry.lock
  pyproject.toml
  worker/block_scraper.py
  worker/block_tracker.py
  worker/brave_handler.py
  worker/manual_signer.py
  worker/tx_tracker.py
  worker/worker_cdk_stack.py
Labels: Large

#109 Backmerge 0.2.1 to development
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/utils/_graphql.py
  poetry.lock
  pyproject.toml
  worker/block_scraper.py
  worker/block_tracker.py
  worker/brave_handler.py
  worker/manual_signer.py
  worker/tx_tracker.py
  worker/worker_cdk_stack.py
Labels: Large
